name: action
description: first action
inputs:
  action-first:
    description: "My first action"
    required: false
    default: "first"
  path_dockerfile:
    required: false
    default: "Dockerfile" 
  image_name:
    required: true
  tag_name:
    required: false
    default: "Optional"
  
runs:
  using: composite
  steps: 
    - run:  |
        if [ -z "${{ inputs.tag_name}}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name}}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV
        docker build . --file {{inputs.path_dockerfile}} --tag academy:$(date +%s)
      shell: bash