name: action
description: first action
inputs:
  action-first:
    description: "My first action"
    required: false
    default: "first"
  path_dockerfile:
    required: false
    default: "Dockerfile" 
  image_name:
    required: true
  tag_name:
    required: false
    default: "Optional"
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.EXERCISE }}

runs:
  using: composite
  steps: 
    - run:  |
        if [ -z "${{ inputs.tag_name}}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name}}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=${{ inputs.image_name}}" >> $GITHUB_ENV
        docker build . --file "${{ inputs.path_dockerfile }}" --tag academy:$(date +%s)
      shell: bash