name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  login:

    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.exercise }}


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: bernardosilva173/academy/.github/actions/docker_build@main
      with:
        tag_name: latest
        image_name: day2
    - name: list Docker images
      run: docker images

