name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: bernardosilva173/academy/.github/actions/docker_build@main
    - name: list Docker images
      run: docker images
      with:
        tag_name: latest

